/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    products: Product;
    'product-categories': ProductCategory;
    projects: Project;
    'project-categories': ProjectCategory;
    articles: Article;
    'article-categories': ArticleCategory;
    catalogs: Catalog;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'product-categories': ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'project-categories': ProjectCategoriesSelect<false> | ProjectCategoriesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'article-categories': ArticleCategoriesSelect<false> | ArticleCategoriesSelect<true>;
    catalogs: CatalogsSelect<false> | CatalogsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('fa' | 'en' | 'ar') | ('fa' | 'en' | 'ar')[];
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    careers: Career;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    careers: CareersSelect<false> | CareersSelect<true>;
  };
  locale: 'fa' | 'en' | 'ar';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  subtitle?: string | null;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  status: 'draft' | 'published';
  publishedAt?: string | null;
  /**
   * URL segment. Shared across all languages.
   */
  slug: string;
  /**
   * Leave empty to derive from the content itself.
   */
  seo?: {
    /**
     * Overrides <title>. Aim for 50–60 characters.
     */
    title?: string | null;
    /**
     * Overrides the meta description. Aim for 150–160 characters.
     */
    description?: string | null;
    /**
     * Comma separated. Low weight for ranking; used sparingly.
     */
    keywords?: string | null;
    /**
     * OpenGraph image. Falls back to the cover image.
     */
    image?: (number | null) | Media;
    /**
     * Absolute URL. Only set when this page duplicates another.
     */
    canonical?: string | null;
    /**
     * Exclude from search engines and from the sitemap.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers and for search engines. Required.
   */
  alt: string;
  caption?: string | null;
  credit?: string | null;
  /**
   * Include this image on the public gallery page.
   */
  showInGallery?: boolean | null;
  galleryCategory?: ('factory' | 'products' | 'projects' | 'team') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * Shown on product cards and in search results.
   */
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Used on cards, in OpenGraph and as the gallery poster.
   */
  coverImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Rendered as the technical specifications table.
   */
  specifications?:
    | {
        label: string;
        value: string;
        unit?: string | null;
        id?: string | null;
      }[]
    | null;
  applications?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  downloads?: (number | Catalog)[] | null;
  relatedProducts?: (number | Product)[] | null;
  category: number | ProductCategory;
  /**
   * Show on the homepage.
   */
  featured?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  /**
   * URL segment. Shared across all languages.
   */
  slug: string;
  /**
   * Leave empty to derive from the content itself.
   */
  seo?: {
    /**
     * Overrides <title>. Aim for 50–60 characters.
     */
    title?: string | null;
    /**
     * Overrides the meta description. Aim for 150–160 characters.
     */
    description?: string | null;
    /**
     * Comma separated. Low weight for ranking; used sparingly.
     */
    keywords?: string | null;
    /**
     * OpenGraph image. Falls back to the cover image.
     */
    image?: (number | null) | Media;
    /**
     * Absolute URL. Only set when this page duplicates another.
     */
    canonical?: string | null;
    /**
     * Exclude from search engines and from the sitemap.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalogs".
 */
export interface Catalog {
  id: number;
  title: string;
  description?: string | null;
  category?: ('product' | 'datasheet' | 'certificate' | 'profile') | null;
  cover?: (number | null) | Media;
  language?: ('fa' | 'en' | 'ar')[] | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories".
 */
export interface ProductCategory {
  id: number;
  title: string;
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  /**
   * URL segment. Shared across all languages.
   */
  slug: string;
  /**
   * Leave empty to derive from the content itself.
   */
  seo?: {
    /**
     * Overrides <title>. Aim for 50–60 characters.
     */
    title?: string | null;
    /**
     * Overrides the meta description. Aim for 150–160 characters.
     */
    description?: string | null;
    /**
     * Comma separated. Low weight for ranking; used sparingly.
     */
    keywords?: string | null;
    /**
     * OpenGraph image. Falls back to the cover image.
     */
    image?: (number | null) | Media;
    /**
     * Absolute URL. Only set when this page duplicates another.
     */
    canonical?: string | null;
    /**
     * Exclude from search engines and from the sitemap.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  summary?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  videos?:
    | {
        url: string;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  client?: string | null;
  location?: string | null;
  /**
   * Gregorian year of completion.
   */
  year?: number | null;
  productsUsed?: (number | Product)[] | null;
  technicalInfo?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  category: number | ProjectCategory;
  /**
   * Show on the homepage.
   */
  featured?: boolean | null;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  /**
   * URL segment. Shared across all languages.
   */
  slug: string;
  /**
   * Leave empty to derive from the content itself.
   */
  seo?: {
    /**
     * Overrides <title>. Aim for 50–60 characters.
     */
    title?: string | null;
    /**
     * Overrides the meta description. Aim for 150–160 characters.
     */
    description?: string | null;
    /**
     * Comma separated. Low weight for ranking; used sparingly.
     */
    keywords?: string | null;
    /**
     * OpenGraph image. Falls back to the cover image.
     */
    image?: (number | null) | Media;
    /**
     * Absolute URL. Only set when this page duplicates another.
     */
    canonical?: string | null;
    /**
     * Exclude from search engines and from the sitemap.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-categories".
 */
export interface ProjectCategory {
  id: number;
  title: string;
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  /**
   * URL segment. Shared across all languages.
   */
  slug: string;
  /**
   * Leave empty to derive from the content itself.
   */
  seo?: {
    /**
     * Overrides <title>. Aim for 50–60 characters.
     */
    title?: string | null;
    /**
     * Overrides the meta description. Aim for 150–160 characters.
     */
    description?: string | null;
    /**
     * Comma separated. Low weight for ranking; used sparingly.
     */
    keywords?: string | null;
    /**
     * OpenGraph image. Falls back to the cover image.
     */
    image?: (number | null) | Media;
    /**
     * Absolute URL. Only set when this page duplicates another.
     */
    canonical?: string | null;
    /**
     * Exclude from search engines and from the sitemap.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * Shown on cards and used as the meta description fallback.
   */
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  coverImage?: (number | null) | Media;
  /**
   * Estimated reading time. Leave empty to hide.
   */
  readingMinutes?: number | null;
  tags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  author?: (number | null) | User;
  category: number | ArticleCategory;
  featured?: boolean | null;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  /**
   * URL segment. Shared across all languages.
   */
  slug: string;
  /**
   * Leave empty to derive from the content itself.
   */
  seo?: {
    /**
     * Overrides <title>. Aim for 50–60 characters.
     */
    title?: string | null;
    /**
     * Overrides the meta description. Aim for 150–160 characters.
     */
    description?: string | null;
    /**
     * Comma separated. Low weight for ranking; used sparingly.
     */
    keywords?: string | null;
    /**
     * OpenGraph image. Falls back to the cover image.
     */
    image?: (number | null) | Media;
    /**
     * Absolute URL. Only set when this page duplicates another.
     */
    canonical?: string | null;
    /**
     * Exclude from search engines and from the sitemap.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-categories".
 */
export interface ArticleCategory {
  id: number;
  title: string;
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  /**
   * URL segment. Shared across all languages.
   */
  slug: string;
  /**
   * Leave empty to derive from the content itself.
   */
  seo?: {
    /**
     * Overrides <title>. Aim for 50–60 characters.
     */
    title?: string | null;
    /**
     * Overrides the meta description. Aim for 150–160 characters.
     */
    description?: string | null;
    /**
     * Comma separated. Low weight for ranking; used sparingly.
     */
    keywords?: string | null;
    /**
     * OpenGraph image. Falls back to the cover image.
     */
    image?: (number | null) | Media;
    /**
     * Absolute URL. Only set when this page duplicates another.
     */
    canonical?: string | null;
    /**
     * Exclude from search engines and from the sitemap.
     */
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'product-categories';
        value: number | ProductCategory;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'project-categories';
        value: number | ProjectCategory;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'article-categories';
        value: number | ArticleCategory;
      } | null)
    | ({
        relationTo: 'catalogs';
        value: number | Catalog;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  heroImage?: T;
  content?: T;
  status?: T;
  publishedAt?: T;
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        image?: T;
        canonical?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  shortDescription?: T;
  description?: T;
  coverImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  specifications?:
    | T
    | {
        label?: T;
        value?: T;
        unit?: T;
        id?: T;
      };
  applications?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  downloads?: T;
  relatedProducts?: T;
  category?: T;
  featured?: T;
  sortOrder?: T;
  status?: T;
  publishedAt?: T;
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        image?: T;
        canonical?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  sortOrder?: T;
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        image?: T;
        canonical?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  description?: T;
  coverImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  videos?:
    | T
    | {
        url?: T;
        title?: T;
        id?: T;
      };
  client?: T;
  location?: T;
  year?: T;
  productsUsed?: T;
  technicalInfo?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  category?: T;
  featured?: T;
  status?: T;
  publishedAt?: T;
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        image?: T;
        canonical?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-categories_select".
 */
export interface ProjectCategoriesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  sortOrder?: T;
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        image?: T;
        canonical?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  content?: T;
  coverImage?: T;
  readingMinutes?: T;
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  author?: T;
  category?: T;
  featured?: T;
  status?: T;
  publishedAt?: T;
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        image?: T;
        canonical?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "article-categories_select".
 */
export interface ArticleCategoriesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  sortOrder?: T;
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        image?: T;
        canonical?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalogs_select".
 */
export interface CatalogsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  category?: T;
  cover?: T;
  language?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  showInGallery?: T;
  galleryCategory?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  /**
   * Used when a page has no description of its own.
   */
  defaultSeoDescription?: string | null;
  /**
   * Fallback OpenGraph image, ideally 1200×630.
   */
  defaultOgImage?: (number | null) | Media;
  logo?: (number | null) | Media;
  logoDark?: (number | null) | Media;
  address?: string | null;
  phones?:
    | {
        label?: string | null;
        number: string;
        id?: string | null;
      }[]
    | null;
  emails?:
    | {
        label?: string | null;
        address: string;
        id?: string | null;
      }[]
    | null;
  openingHours?: string | null;
  /**
   * Optional map iframe URL shown on the contact page.
   */
  mapEmbedUrl?: string | null;
  /**
   * Where contact form notifications are sent.
   */
  notificationEmail?: string | null;
  social?:
    | {
        platform: 'linkedin' | 'instagram' | 'telegram' | 'youtube' | 'x' | 'aparat';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The four numbers shown on the homepage.
   */
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero?: {
    title?: string | null;
    subtitle?: string | null;
    /**
     * Image or short MP4 used from the `md` breakpoint up.
     */
    desktopMedia?: (number | null) | Media;
    /**
     * Always an image — never a video on mobile data.
     */
    mobileImage?: (number | null) | Media;
    /**
     * Percentage of dark overlay, for text contrast.
     */
    overlayOpacity?: number | null;
    primaryCta?: {
      label?: string | null;
      href?: string | null;
    };
    secondaryCta?: {
      label?: string | null;
      href?: string | null;
    };
  };
  /**
   * Turn homepage sections on or off without a deploy.
   */
  sections?: {
    showIntro?: boolean | null;
    showStats?: boolean | null;
    showProducts?: boolean | null;
    showProjects?: boolean | null;
    showProduction?: boolean | null;
    showQuality?: boolean | null;
    showSustainability?: boolean | null;
    showArticles?: boolean | null;
  };
  intro?: {
    title?: string | null;
    body?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers".
 */
export interface Career {
  id: number;
  intro?: string | null;
  applyEmail?: string | null;
  positions?:
    | {
        title: string;
        department?: string | null;
        location?: string | null;
        employmentType?: ('full-time' | 'part-time' | 'contract' | 'internship') | null;
        description?: string | null;
        open?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  defaultSeoDescription?: T;
  defaultOgImage?: T;
  logo?: T;
  logoDark?: T;
  address?: T;
  phones?:
    | T
    | {
        label?: T;
        number?: T;
        id?: T;
      };
  emails?:
    | T
    | {
        label?: T;
        address?: T;
        id?: T;
      };
  openingHours?: T;
  mapEmbedUrl?: T;
  notificationEmail?: T;
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        desktopMedia?: T;
        mobileImage?: T;
        overlayOpacity?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  sections?:
    | T
    | {
        showIntro?: T;
        showStats?: T;
        showProducts?: T;
        showProjects?: T;
        showProduction?: T;
        showQuality?: T;
        showSustainability?: T;
        showArticles?: T;
      };
  intro?:
    | T
    | {
        title?: T;
        body?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers_select".
 */
export interface CareersSelect<T extends boolean = true> {
  intro?: T;
  applyEmail?: T;
  positions?:
    | T
    | {
        title?: T;
        department?: T;
        location?: T;
        employmentType?: T;
        description?: T;
        open?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}